add describe to most scripts.

diff --git a/.local/bin/mybin/fmenu b/.local/bin/mybin/fmenu
--- a/.local/bin/mybin/fmenu
+++ b/.local/bin/mybin/fmenu
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# Alternative of dmenu but using terminal and fzf.
+
 if [ $(pgrep -c "$(basename "$0")") -gt 1 ]; then
 	echo 'Other fmenu is running!' >&2
 	exit 1
@@ -14,7 +16,7 @@ fontsize='20'
 
 # parse options
 TEMP=$(getopt -o 'p:l:c:f:z:' -n "$0" -- "$@")
-[ $? -ne 0 ] && echo 'Parsing options error!' >&2 && exit 1
+[ $? -ne 0 ] && echo 'Failed to parsing options!' >&2 && exit 1
 eval set -- "$TEMP"
 unset TEMP
 
