fix vol

diff --git a/.local/bin/system/vl b/.local/bin/system/vl
--- a/.local/bin/system/vl
+++ b/.local/bin/system/vl
@@ -32,16 +32,21 @@ switch() {
 }
 
 get_volume() {
+	if [ "$(pactl get-sink-mute @DEFAULT_SINK@)" = 'Mute: yes' ]; then
+		printf 'muted\n'
+		return
+	fi
 	pactl get-sink-volume @DEFAULT_SINK@ | sed 's/.* \([0-9]*\)% .*/\1/; q'
 }
 
 case $1 in
 	u|up) up "$2" ;;
 	d|down) down "$2" ;;
-	sink-mute) sink_mute ;;
+	mute|sink-mute) sink_mute ;;
 	source-mute) source_mute ;;
 	switch) switch ;;
 	''|get-volume) get_volume ;;
+	*) echo "${0##*/}: option $1 not found." >&2 && exit 1;;
 esac
 
 # update bar
